publishpress/PublishPress-Future

.distignore, .gitignore, Gruntfile.js, admin-edit.js, composer.json, languages/post-expirator.pot, package.json, phpcs.xml, post-expirator-debug.php, post-expirator.php
=> fix #19: wpcs compliant code

admin-edit.js, post-expirator.php
=> fix #4: Bulk Edit doesn't work

post-expirator.php
=> fix #29: bulk edit does not change scheduled event

post-expirator.php
=> fix #23: the ExpireType (Draft, Trash, etc.) does not seem to be set

post-expirator.php
=> fix #16: Date not being translated in shortcode

post-expirator.php
=> add error to debug message if schedule cannot be altered

package.json, post-expirator.php, readme.txt
=> fix #34: create changelog, bump version

post-expirator.php
=> fix #43: Support for quotes in Default expiry

functions.php, legacy-functions.php, post-expirator.php
=> fix #40: Expose wrappers for legacy functions

languages/post-expirator.pot, post-expirator.php
#5 
This fixes translation issues in Quick Edit and Bulk Edit as well:
=> fix #5: translation bug

post-expirator.php
=> fix #46: default day and year if fields are left empty

legacy-functions.php
=> fix #60: Plugin conflict with WCFM

post-expirator.php
=> Bug with "Category: Remove"

post-expirator.php
=> fix #56: Hide metabox from Media Library files

classes/Display.class.php, languages/post-expirator.pot, views/menu-defaults.php, views/menu-diagnostics.php, views/menu-general.php, views/tabs.php
=> separate markup into views

assets/js/settings.js, classes/Display.class.php, classes/Facade.class.php, languages/post-expirator.pot, post-expirator.php, views/menu-defaults.php, views/menu-general.php
=> fix #12: set a default time

admin-edit.js, classes/Display.class.php, languages/post-expirator.pot, legacy-functions.php, post-expirator.php, views/bulk-edit.php, views/expire-column.php, views/how-to-expire.php, views/menu-defaults.php, views/quick-edit.php
=> fix #62: how to expire in quick and bulk edit

assets/css/settings.css, assets/js/settings.js, languages/post-expirator.pot, views/tabs.php
=> use WP tabs

languages/post-expirator.pot, views/bulk-edit.php, views/expire-column.php
#12 
https://github.com/publishpress/PublishPress-Future/issues/12#issuecomment-901128626
=> use default time in quick and bulk edit

languages/post-expirator.pot, post-expirator.php
=> Stop the Post Expirator box from appearing in non-public post types

classes/Facade.class.php, languages/post-expirator.pot, post-expirator.php
=> by default show metabox only in post and pages

views/menu-defaults.php
=> by default consider metabox active only in post and pages

classes/Facade.class.php
=> fix #92: PHP notice

classes/Display.class.php
=> fix #94: Default Expiration Categories cannot be unset

assets/css/style.css, languages/post-expirator.pot, post-expirator.php, views/classic-metabox.php, views/how-to-expire.php
=> fix #83:Tidy up design for Classic Editor version

classes/Display.class.php, languages/post-expirator.pot, views/menu-display.php, views/menu-editor.php, views/menu-general.php, views/tabs.php
Have combined #97 #98 #99 into this PR as all of them modified the same component
=> #97 #98 #99: modify tabs

RoboFile.php, post-expirator.php
=> fix #110: Error with 2.5.0 and WordPress 5.8.1

phpcs.xml, post-expirator.php
=> #116: Showing too many post types

post-expirator.php, views/bulk-edit.php, views/quick-edit.php
=> fix #110: error on php8

readme.txt
=> fix #125: update contributors

assets/css/settings.css, classes/Display.class.php, classes/Facade.class.php, composer.json, package.json, post-expirator.php, views/menu-general.php
=> Hotfix 141 capability expire

readme.txt
=> Update stable version

post-expirator.php
=> Fix undefined array key hook_suffix, #259

src/Framework/WordPress/Models/PostModel.php
=> Fix hook transition_post_status running twice

composer.json, legacy/functions.php, post-expirator.php, readme.txt, services.php, src/Core/DI/ServicesAbstract.php, src/Framework/WordPress/Models/PostModel.php, src/Modules/Expirator/ExpirationActions/PostCategoryRemove.php, src/Modules/Expirator/ExpirationActions/PostCategorySet.php, src/Modules/Expirator/ExpirationScheduler.php, src/Modules/Expirator/HooksAbstract.php, src/Modules/Expirator/Migrations/V30000WPCronToActionsScheduler.php, src/Modules/Expirator/Migrations/V30001RestorePostMeta.php, src/Modules/Expirator/Models/DefaultDataModel.php, src/Modules/Expirator/Models/ExpirablePostModel.php, src/Modules/Expirator/Schemas/ActionArgsSchema.php, src/Modules/Expirator/Tables/ScheduledActionsTable.php, src/Modules/Settings/Controllers/Controller.php, src/Modules/Settings/Module.php, src/Views/menu-diagnostics.php, src/Views/menu-tools.php, tests/codeception/wpunit/Modules/Expirator/Schemas/ActionArgsSchemaTest.php
=> Release 3.0.1

src/Modules/Expirator/Schemas/ActionArgsSchema.php
Table creation silently fails on a database with the InnoDB engine disabled. We should respect the user's choice of DB engine by using the default.
Remove the explicit choice of InnoDB as database engine for the action_args table.
Users who have chosen to use a different database engine to InnoDB will be able to install the plugin. Wordpress doesn't enforce engine type so the plugin will be using the same engine as Wordpress itself, possibly giving performance / stability improvements.
None known.
=> Don't hard-code DB engine when creating table

legacy/classes/Display.class.php, src/Modules/Expirator/Models/DefaultDataModel.php, src/Modules/Settings/Controllers/Controller.php
=> Fix #566 with better sanitization for custom date offset

src/Modules/Expirator/ExpirationScheduler.php, src/Modules/Expirator/Models/ActionArgsModel.php
We are getting this hour issue during saving the post. Hour is reduced every time we are saving the post and the timezone settings is already correct.
https://github.com/publishpress/PublishPress-Future/assets/6133482/7924bc49-def0-478f-a02a-bc3e2ce38a78
It will fix the hour changing issue
- [ x] I have created a specific branch for this pull request before committing, starting off the current HEAD of `development` branch. 
- [x ] I'm submitting to the `development`, feature/hotfix/release branch. (Do not submit to the master branch!)
- [x ] This pull request relates to a specific problem (bug or improvement).
- [x ] I have mentioned the issue number in the pull request description text.
- [x ] All the issues mentioned in this pull request relate to the problem I'm trying to solve.
- [x ] …
=> fix schedule date hour issue

assets/jsx/components/PostTypeSettingsPanel.jsx, assets/jsx/components/PostTypesSettingsPanels.jsx, assets/jsx/components/SettingsFieldset.jsx
=> Add tabs for post types in the post types settings page

assets/jsx/block-editor.jsx, assets/jsx/bulk-edit.jsx, assets/jsx/classic-editor.jsx, assets/jsx/components/FutureActionPanel.jsx, assets/jsx/components/FutureActionPanelBlockEditor.jsx, assets/jsx/components/FutureActionPanelBulkEdit.jsx, assets/jsx/components/FutureActionPanelClassicEditor.jsx, assets/jsx/components/FutureActionPanelQuickEdit.jsx, assets/jsx/quick-edit.jsx, legacy/classes/Display.class.php, src/Modules/Expirator/Controllers/BlockEditorController.php, src/Modules/Expirator/Controllers/BulkEditController.php, src/Modules/Expirator/Controllers/ClassicEditorController.php, src/Modules/Expirator/Controllers/QuickEditController.php, src/Modules/Settings/SettingsFacade.php, src/Views/menu-general.php
=> Add option to hide the calendar by default

assets/css/edit.css, src/Modules/Expirator/Controllers/ClassicEditorController.php
=> Fix support to Event Espresso plugin

CHANGELOG.md, assets/js/blockEditor.js, assets/js/bulkEdit.js, assets/js/classicEditor.js, assets/js/quickEdit.js, assets/js/settingsGeneral.js, assets/js/settingsPostTypes.js, assets/js/workflowEditor.js, assets/jsx/components/DateOffsetPreview.jsx, services.php, src/Core/DI/ServicesAbstract.php, src/Framework/System/DateTimeHandler.php, src/Framework/System/DateTimeHandlerInterface.php, src/Modules/Expirator/Controllers/RestAPIController.php, src/Modules/Expirator/Models/PostTypeDefaultDataModel.php, src/Modules/Expirator/Models/PostTypeDefaultDataModelFactory.php, src/Modules/Expirator/Module.php, tests/Integration/Framework/System/DateTimeHandlerTest.php
=> Fix #1005 fixing date offsets with fixed time

src/Modules/Expirator/Models/ExpirablePostModel.php, src/Modules/Workflows/Domain/Engine/NodeRunnerProcessors/CronStep.php
=> Fix errors generated while merging for the last release

services.php, src/Core/Plugin.php, src/Modules/Expirator/Controllers/ExpirationController.php, src/Modules/Expirator/HooksAbstract.php, src/Modules/Expirator/Models/ExpirablePostModel.php, src/Modules/Expirator/Module.php
=> Fix/1024 zombie auto-drafts

services.php, src/Modules/Expirator/Controllers/RestAPIController.php, src/Modules/Expirator/Module.php, src/Modules/Settings/Models/TaxonomiesModel.php, src/Modules/Workflows/Controllers/ManualPostTrigger.php
Fix #1036 using the logger instead of error_log.
=> Fix 1036 undefined function errorlog

assets/js/workflowEditor.js, assets/jsx/workflow-editor/components/app.jsx, assets/jsx/workflow-editor/components/data-fields/expression-builder/column-item.jsx, assets/jsx/workflow-editor/components/data-fields/expression-builder/columns-container.jsx, assets/jsx/workflow-editor/components/data-types/future-action.jsx, assets/jsx/workflow-editor/components/data-types/index.jsx, assets/jsx/workflow-editor/components/data-types/post.jsx, assets/jsx/workflow-editor/components/data-types/terms-array.jsx, docs/custom-variable-form.md, docs/registering-data-type.md, services.php, src/Modules/Workflows/Domain/Engine/NodeRunnerProcessors/CronStep.php, src/Modules/Workflows/Domain/Engine/NodeRunners/Triggers/CoreOnManuallyEnabledForPost.php, src/Modules/Workflows/Domain/Engine/NodeRunners/Triggers/CoreOnPostUpdated.php, src/Modules/Workflows/Domain/Engine/NodeRunners/Triggers/CoreOnSavePost.php, src/Modules/Workflows/Domain/Engine/NodeRunners/Triggers/FutureLegacyAction.php, src/Modules/Workflows/Domain/Engine/RuntimeVariablesHandler.php, src/Modules/Workflows/Domain/Engine/VariableResolvers/FutureActionResolver.php, src/Modules/Workflows/Domain/Engine/VariableResolvers/PostResolver.php, src/Modules/Workflows/Domain/Engine/VariableResolvers/TermsArrayResolver.php, tests/Integration/Modules/Workflows/Domain/Engine/VaiableResolvers/PostResolverTest.php
Add future action data as a variable in the workflow builder.
=> Fix #948 future action reference

assets/css/workflows-list.css, src/Modules/Workflows/Controllers/WorkflowsList.php
=> Remove items from Quick Edit area of Workflows

assets/css/edit.css, src/Views/expire-column.php
=> Improve the Overdue action message in the posts list removing red icon

composer.json, src/Modules/Workflows/Domain/Steps/Actions/Definitions/ChangePostStatus.php
* Ignore cache file on built package
* Refactor Docker setup for WordPress testing environment
- Updated `docker-compose.yaml` to build WordPress from a local Dockerfile and added MailHog service for email testing.
- Introduced Xdebug configuration and exposed its port for debugging.
- Created a new MySQL configuration file to enable general logging and adjusted SQL modes.
- Added WP-CLI preparation script to automate WordPress installation and plugin setup.
- Removed the Classic Editor plugin from the test data as it is no longer needed.
- Updated test scripts to include MailHog in the setup and cleanup processes.
- Enhanced test output to include MailHog information for easier debugging.
* Refactor RuntimeVariablesHandler and enhance tests
* Fix typo in a test folder name
* Implement …
=> Release/4.5.0 (#1268)

CHANGELOG.md, services.php, src/Modules/Workflows/Domain/Engine/Traits/InfiniteLoopPreventer.php, src/Modules/Workflows/Domain/Steps/Triggers/Runners/OnPostAuthorChangeRunner.php, src/Modules/Workflows/Domain/Steps/Triggers/Runners/OnPostMetaChangeRunner.php, src/Modules/Workflows/Domain/Steps/Triggers/Runners/OnPostPublishRunner.php, src/Modules/Workflows/Domain/Steps/Triggers/Runners/OnPostRowActionRunner.php, src/Modules/Workflows/Domain/Steps/Triggers/Runners/OnPostScheduleRunner.php, src/Modules/Workflows/Domain/Steps/Triggers/Runners/OnPostStatusChangeRunner.php, src/Modules/Workflows/Domain/Steps/Triggers/Runners/OnPostWorkflowEnableRunner.php, src/Modules/Workflows/Domain/Steps/Triggers/Runners/OnUserRoleChangeRunner.php
Fix #1203.
Remove unused InfiniteLoopPreventer trait and adding WorkflowExecutionSafeguard dependency.
Update services.php to include the new safeguard in the service container.
=> Remove unused InfiniteLoopPrever and add execution safeguard dependency

CHANGELOG.md, assets/jsx/workflow-editor/components/data-fields/post-data/index.jsx
This PR Updated Workflow Action "Post Name" to "Post Slug" to fix #1282
=> Update Workflow Action "Post Name" to "Post Slug" #1282

CHANGELOG.md, src/Modules/Workflows/Domain/Steps/Actions/Definitions/UpdatePost.php
Updated Workflow Action "Update post" label and description to fix #1283
=> Update Workflow Action "Update post" label and description #1283

CHANGELOG.md, assets/jsx/workflow-editor/components/secondary-sidebar/menu.jsx
Added Scrollbar to Workflow Editor left sidebar to fix #1281
=> Add Scrollbar for Workflow Editor for left sidebar

CHANGELOG.md, assets/jsx/workflow-editor/components/data-fields/expression-builder/style.css
Workflow editor filter area autocomplete dropdown overlapping content to fix #1303
=> Improve visual selection of filters

CHANGELOG.md, src/Core/HooksAbstract.php, src/Modules/Workflows/Controllers/WorkflowsList.php, src/Modules/Workflows/Interfaces/WorkflowModelInterface.php, src/Modules/Workflows/Models/WorkflowModel.php
Added a "Copy" button to workflows to fix #1183
=> Add a "Copy" button to workflows

CHANGELOG.md, assets/jsx/workflow-editor/components/data-fields/expression-builder/column-item.jsx, assets/jsx/workflow-editor/components/data-fields/expression-builder/columns-container.jsx, assets/jsx/workflow-editor/components/data-types/post.jsx, assets/jsx/workflow-editor/components/data-types/user.jsx, assets/jsx/workflow-editor/components/data-types/workflow.jsx, assets/jsx/workflow-editor/utils.jsx
This pull request Clarify the "Metadata" description by including table name for each metadata to fix #1247
=> Clarity on "Metadata" description

CHANGELOG.md, src/Modules/Workflows/Domain/Steps/Actions/Definitions/DuplicatePost.php, src/Modules/Workflows/Domain/Steps/Actions/Runners/DuplicatePostRunner.php, src/Modules/Workflows/Domain/Steps/Triggers/Runners/OnPostSaveRunner.php, src/Modules/Workflows/Domain/Steps/Triggers/Runners/OnPostUpdateRunner.php, src/Modules/Workflows/Domain/Steps/Triggers/Runners/OnPostWorkflowEnableRunner.php, src/Modules/Workflows/Infrastructure/Safety/WorkflowExecutionSafeguard.php, src/Modules/Workflows/Interfaces/WorkflowExecutionSafeguardInterface.php, src/Modules/Workflows/Models/StepTypesModel.php
Added new  "Duplicate Post" workflow action to fix #1170
=> New action to duplicate post

assets/jsx/workflow-editor/components/data-fields/custom-options/option-item.jsx, src/Modules/Workflows/Domain/Steps/Actions/Definitions/UserInteraction.php
=> Extra text not needed for Interactive Delay

CHANGELOG.md, src/Modules/Expirator/Controllers/BlockEditorController.php
Future Actions missing in post editor to fix #1372
=> Future Actions missing in post editor #1372

src/Modules/Expirator/Controllers/PluginsListController.php
Add plugin list Upgrade to Pro color class
=> 1360-Key-links-on-Plugins-screen 

CHANGELOG.md, src/Modules/Workflows/Domain/Steps/Actions/Definitions/UserInteraction.php
Update the field description Text on User interaction step to fix #1384
=> Text on User interaction

CHANGELOG.md, assets/jsx/workflow-editor/components/data-fields/conditional/components/conditional-hoc.jsx, assets/jsx/workflow-editor/components/data-fields/post-filter/components/post-filter.jsx, src/Modules/Workflows/Domain/Steps/Actions/Definitions/Conditional.php, src/Modules/Workflows/Domain/Steps/Triggers/Definitions/OnPostAuthorChange.php, src/Modules/Workflows/Domain/Steps/Triggers/Definitions/OnPostMetaChange.php, src/Modules/Workflows/Domain/Steps/Triggers/Definitions/OnPostPublish.php, src/Modules/Workflows/Domain/Steps/Triggers/Definitions/OnPostRowAction.php, src/Modules/Workflows/Domain/Steps/Triggers/Definitions/OnPostSave.php, src/Modules/Workflows/Domain/Steps/Triggers/Definitions/OnPostSchedule.php, src/Modules/Workflows/Domain/Steps/Triggers/Definitions/OnPostStatusChange.php, src/Modules/Workflows/Domain/Steps/Triggers/Definitions/OnPostUpdate.php, src/Modules/Workflows/Domain/Steps/Triggers/Definitions/OnPostWorkflowEnable.php
Consistency with "Filters" name to fix #1296
=> Consistency with "Filters" name

CHANGELOG.md, post-expirator.php
Plugin's text domain is loaded too early to fix #1350
=> Plugin's text domain is loaded too early

CHANGELOG.md, assets/js/blockEditor.js, assets/js/bulkEdit.js, assets/js/classicEditor.js, assets/js/quickEdit.js, assets/js/settingsGeneral.js, assets/js/settingsPostTypes.js, assets/jsx/components/FutureActionPanel.jsx, src/Modules/Expirator/Controllers/RestAPIController.php, src/Modules/Expirator/ExpirationScheduler.php, src/Modules/Expirator/Models/ExpirablePostModel.php, src/Modules/Workflows/Domain/LegacyAction/TriggerWorkflow.php, src/Modules/Workflows/Domain/Steps/Triggers/Runners/OnLegacyActionTriggerRunner.php
This Pr fixes issue with Manually run via Future Actions box not working in Gutenberg Editor to fix #1405
=> Manually run via Future Actions box not working in Gutenberg Editor #1405

CHANGELOG.md, src/Core/HooksAbstract.php
Add updated_post_meta and added_post_meta to core HooksAbstract fix #1416
=> Add updated_post_meta and added_post_meta to core HooksAbstract
